# -*- coding: utf-8 -*-
"""self_pruning_network.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uxl9ACTvWXbVyUBGEktYCIAdY6mjWKSu
"""

import math
import csv
import time
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
import torchvision
import torchvision.transforms as transforms
import matplotlib
matplotlib.use("Agg")          # headless – no display required
import matplotlib.pyplot as plt

class PrunableLinear(nn.Module):
    def __init__(self, in_features: int, out_features: int, bias: bool = True):
        super().__init__()
        self.in_features  = in_features
        self.out_features = out_features

        # ── Standard weight & bias (same init as nn.Linear) ──────────────────
        self.weight = nn.Parameter(torch.empty(out_features, in_features))
        self.bias   = nn.Parameter(torch.empty(out_features)) if bias else None

        # ── Gate scores – same shape as weight ───────────────────────────────
        # Initialised near 0 so sigmoid ≈ 0.5; the network starts "half-open"
        # and learns to either open (→ 1) or close (→ 0) each gate.
        self.gate_scores = nn.Parameter(torch.empty(out_features, in_features))

        self._reset_parameters()

    def _reset_parameters(self):
        # Kaiming uniform (same as default nn.Linear)
        nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))
        if self.bias is not None:
            fan_in, _ = nn.init._calculate_fan_in_and_fan_out(self.weight)
            bound = 1 / math.sqrt(fan_in) if fan_in > 0 else 0
            nn.init.uniform_(self.bias, -bound, bound)
        # Gate scores: small random values → sigmoid starts close to 0.5
        nn.init.normal_(self.gate_scores, mean=0.0, std=0.01)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        gates         = torch.sigmoid(self.gate_scores)   # ∈ (0, 1)
        pruned_weight = self.weight * gates               # element-wise
        return F.linear(x, pruned_weight, self.bias)      # gradients flow ✓

    def get_gates(self) -> torch.Tensor:
        """Return current gate values (detached, for monitoring)."""
        return torch.sigmoid(self.gate_scores).detach()

    def extra_repr(self) -> str:
        return (f"in_features={self.in_features}, "
                f"out_features={self.out_features}, "
                f"bias={self.bias is not None}")

class SelfPruningNet(nn.Module):
    def __init__(self, hidden_dims=(1024, 512, 256)):
        super().__init__()

        input_dim = 3 * 32 * 32   # 3072

        layers = []
        prev = input_dim
        for h in hidden_dims:
            layers.append(PrunableLinear(prev, h))
            layers.append(nn.BatchNorm1d(h))
            layers.append(nn.ReLU(inplace=True))
            layers.append(nn.Dropout(0.3))
            prev = h

        self.features   = nn.Sequential(*layers)
        self.classifier = PrunableLinear(prev, 10)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x.view(x.size(0), -1)   # flatten
        x = self.features(x)
        return self.classifier(x)

    def prunable_layers(self):
        """Yield all PrunableLinear sub-modules."""
        for module in self.modules():
            if isinstance(module, PrunableLinear):
                yield module

def sparsity_loss(model: SelfPruningNet) -> torch.Tensor:
    total = torch.tensor(0.0, device=next(model.parameters()).device)
    for layer in model.prunable_layers():
        gates = torch.sigmoid(layer.gate_scores)   # keep in graph!
        total = total + gates.sum()
    return total

import torchvision
torchvision.datasets.CIFAR10(root="./data", train=True, download=True)
torchvision.datasets.CIFAR10(root="./data", train=False, download=True)

def get_dataloaders(batch_size: int = 128, data_dir: str = "./data"):
    """Download CIFAR-10 and return train / test DataLoaders."""

    train_transform = transforms.Compose([
        transforms.RandomHorizontalFlip(),
        transforms.RandomCrop(32, padding=4),
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465),
                             (0.2470, 0.2435, 0.2616)),
    ])
    test_transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465),
                             (0.2470, 0.2435, 0.2616)),
    ])

    train_set = torchvision.datasets.CIFAR10(
        root=data_dir, train=True,  download=True, transform=train_transform)
    test_set  = torchvision.datasets.CIFAR10(
        root=data_dir, train=False, download=True, transform=test_transform)

    train_loader = DataLoader(train_set, batch_size=batch_size,
                              shuffle=True,  num_workers=2, pin_memory=True)
    test_loader  = DataLoader(test_set,  batch_size=256,
                              shuffle=False, num_workers=2, pin_memory=True)
    return train_loader, test_loader

def train_one_epoch(model, loader, optimizer, lam, device):
    model.train()
    running_cls_loss  = 0.0
    running_spar_loss = 0.0
    correct = total = 0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()

        logits = model(images)

        cls_loss  = F.cross_entropy(logits, labels)
        spar      = sparsity_loss(model)
        loss      = cls_loss + lam * spar

        loss.backward()
        optimizer.step()

        running_cls_loss  += cls_loss.item()
        running_spar_loss += spar.item()
        preds    = logits.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total   += labels.size(0)

    n = len(loader)
    return (running_cls_loss / n,
            running_spar_loss / n,
            100.0 * correct / total)

@torch.no_grad()
def evaluate(model, loader, device):
    model.eval()
    correct = total = 0
    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)
        preds  = model(images).argmax(dim=1)
        correct += (preds == labels).sum().item()
        total   += labels.size(0)
    return 100.0 * correct / total


def compute_sparsity(model, threshold: float = 1e-2) -> float:
    """
    Fraction of weights whose gate value is below `threshold`.
    Gate ≈ 0 means the weight is effectively pruned.
    """
    pruned = total = 0
    for layer in model.prunable_layers():
        gates  = layer.get_gates()
        pruned += (gates < threshold).sum().item()
        total  += gates.numel()
    return 100.0 * pruned / total if total > 0 else 0.0

def plot_gate_distribution(model, lam: float, save_path: str = "gate_distribution.png"):
    all_gates = []
    for layer in model.prunable_layers():
        all_gates.append(layer.get_gates().cpu().flatten())

    all_gates = torch.cat(all_gates).numpy()

    fig, ax = plt.subplots(figsize=(9, 5))
    ax.hist(all_gates, bins=100, color="#4C72B0", edgecolor="white", linewidth=0.4)
    ax.set_xlabel("Gate Value (sigmoid output)", fontsize=12)
    ax.set_ylabel("Count", fontsize=12)
    ax.set_title(
        f"Distribution of Gate Values  |  λ = {lam}\n"
        f"Spike near 0 = pruned weights   |   Right cluster = active weights",
        fontsize=12,
    )
    ax.axvline(1e-2, color="red", linestyle="--", linewidth=1.2, label="Prune threshold (0.01)")
    ax.legend(fontsize=10)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.close()
    print(f"  → Gate distribution plot saved to '{save_path}'")

def run_experiment(lam: float,
                   train_loader,
                   test_loader,
                   device,
                   epochs: int = 25,
                   lr: float = 1e-3) -> dict:
    """Train the self-pruning network with a given λ and return metrics."""

    print(f"\n{'='*65}")
    print(f"  Experiment  |  λ = {lam}")
    print(f"{'='*65}")

    model     = SelfPruningNet(hidden_dims=(1024, 512, 256)).to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    best_acc = 0.0

    for epoch in range(1, epochs + 1):
        t0 = time.time()
        cls_l, spar_l, train_acc = train_one_epoch(
            model, train_loader, optimizer, lam, device)
        test_acc  = evaluate(model, test_loader, device)
        sparsity  = compute_sparsity(model)
        scheduler.step()
        elapsed = time.time() - t0

        if test_acc > best_acc:
            best_acc = test_acc

        print(f"  Epoch {epoch:02d}/{epochs}  "
              f"cls={cls_l:.3f}  spar={spar_l:.1f}  "
              f"train={train_acc:.1f}%  test={test_acc:.1f}%  "
              f"sparse={sparsity:.1f}%  ({elapsed:.1f}s)")

    final_acc      = evaluate(model, test_loader, device)
    final_sparsity = compute_sparsity(model)

    print(f"\n  ── Final results for λ={lam} ──────────────────────────────")
    print(f"     Test Accuracy : {final_acc:.2f}%")
    print(f"     Sparsity Level: {final_sparsity:.2f}%")

    return {
        "lambda"        : lam,
        "test_accuracy" : round(final_acc, 2),
        "sparsity_pct"  : round(final_sparsity, 2),
        "model"         : model,
    }

def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\nUsing device: {device}")

    train_loader, test_loader = get_dataloaders(batch_size=128)

    # ── Three λ values: low / medium / high ──────────────────────────────────
    lambdas = [1e-5, 1e-4, 1e-3]

    results      = []
    best_result  = None

    for lam in lambdas:
        result = run_experiment(
            lam=lam,
            train_loader=train_loader,
            test_loader=test_loader,
            device=device,
            epochs=25,
            lr=1e-3,
        )
        results.append(result)

        # Track best model (highest accuracy)
        if best_result is None or result["test_accuracy"] > best_result["test_accuracy"]:
            best_result = result

    # ── Summary Table ─────────────────────────────────────────────────────────
    print(f"\n{'='*55}")
    print("  RESULTS SUMMARY")
    print(f"{'='*55}")
    print(f"  {'Lambda':<12} {'Test Acc (%)':>14} {'Sparsity (%)':>14}")
    print(f"  {'-'*42}")
    for r in results:
        print(f"  {r['lambda']:<12} {r['test_accuracy']:>14.2f} {r['sparsity_pct']:>14.2f}")
    print(f"{'='*55}")

    # ── Save CSV ──────────────────────────────────────────────────────────────
    csv_path = "results_table.csv"
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(
            f, fieldnames=["lambda", "test_accuracy", "sparsity_pct"])
        writer.writeheader()
        for r in results:
            writer.writerow({k: v for k, v in r.items() if k != "model"})
    print(f"\n  Results saved to '{csv_path}'")

    # ── Gate distribution plot for best model ────────────────────────────────
    plot_gate_distribution(
        best_result["model"],
        lam=best_result["lambda"],
        save_path="gate_distribution.png",
    )

    print("\nDone.\n")


if __name__ == "__main__":
    main()